name: Unity Build

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: webbertakken/unity-actions@v2
        with:
          unityVersion: 2020.3.x # Set your Unity version

      - name: Install dependencies
        run: |
          # Install any necessary dependencies here (e.g., if you use assets from the Asset Store)

      - name: Build Unity project
        run: |
          # Your build command here, e.g.,
          # Unity -batchmode -quit -executeMethod YourBuildScript.YourBuildMethod

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: BuildFolder # Change to your actual build folder
